SET 'auto.offset.reset' = 'earliest';
--DEFINE oracle_db_name = 'ORAHOM';

CREATE STREAM IF NOT EXISTS USER_POSTGRESQL AS SELECT 
    after -> ID AS ID,
    after -> USER_NAME AS USER_NAME,
    after -> E_MAIL AS E_MAIL,
    after -> USER_PASSWORD AS USER_PASSWORD,
    after -> CPF AS CPF,
    after -> USER_ESPA AS USER_ESPA,
    op VARCHAR
FROM STR_USER_POSTGRESQL;

CREATE STREAM IF NOT EXISTS USER_ADDRESS_POSTGRESQL AS SELECT 
    after -> ID AS ID,
    after -> CEP AS CEP,
    after -> COUNTRY AS COUNTRY,
    after -> REGION AS REGION,
    after -> CITY AS CITY,
    after -> DISTRICT AS DISTRICT,
    after -> STREET AS STREET,
    after -> STREET_NUMBER AS STREET_NUMBER,
    after -> USER_ADDRESS_ESPA AS USER_ADDRESS_ESPA,
    after -> USER_ID AS USER_ID,
    op VARCHAR
FROM STR_USER_ADDRESS_POSTGRESQL;

CREATE STREAM IF NOT EXISTS SINK_USER_SQLSERVER AS SELECT
    up.USER_NAME AS USER_NAME,
    up.E_MAIL AS E_MAIL,
    up.USER_PASSWORD AS USER_PASSWORD,
    up.CPF AS CPF,
    220000 AS USER_ESPA,
    uap.CEP AS CEP,
    uap.COUNTRY AS COUNTRY,
    uap.REGION AS REGION,
    uap.CITY AS CITY,
    uap.DISTRICT AS DISTRICT,
    uap.STREET AS STREET,
    uap.STREET_NUMBER AS STREET_NUMBER,
    uap.USER_ID
FROM USER_POSTGRESQL up
    INNER JOIN USER_ADDRESS_POSTGRESQL uap WITHIN 7 DAYS ON up.ID  = uap.USER_ID 
WHERE up.USER_ESPA <> '880000' OR uap.USER_ADDRESS_ESPA <> '880000';

CREATE STREAM IF NOT EXISTS STR_USER_PURCHASE_POSTGRESQL (
    after STRUCT <
        ID VARCHAR,
        VALUE_PURCHASE VARCHAR,
        USER_PURCHASE_ESPA VARCHAR,
        USER_ADDRESS_ID VARCHAR
    >,
    op VARCHAR
) WITH (KAFKA_TOPIC='postgresql.public.user_', VALUE_FORMAT='JSON');

CREATE STREAM IF NOT EXISTS USER_PURCHASE_POSTGRESQL AS SELECT 
    after -> ID AS ID,
    after -> VALUE_PURCHASE AS VALUE_PURCHASE,
    after -> USER_PURCHASE_ESPA AS USER_PURCHASE_ESPA,
    after -> USER_ADDRESS_ID AS USER_ADDRESS_ID
FROM STR_USER_PURCHASE_POSTGRESQL;

CREATE STREAM IF NOT EXISTS SINK_USER_PURCHASE_SQLSERVER AS SELECT
    upp.VALUE_PURCHASE AS VALUE_PURCHASE,
    us.ID AS USER_ID,
    220000 AS USER_PURCHASE_ESPA,
    us.CPF
FROM USER_PURCHASE_POSTGRESQL upp 
    INNER JOIN USER_ADDRESS_POSTGRESQL uap WITHIN 7 DAYS ON upp.USER_ADDRESS_ID = uap.ID
    INNER JOIN USER_POSTGRESQL up WITHIN 7 DAYS ON up.ID = uap.USER_ID
    INNER JOIN USER_SQLSERVER us WITHIN 7 DAYS ON up.CPF = us.CPF
WHERE USER_PURCHASE_ESPA <> '880000';