SET 'auto.offset.reset' = 'earliest';
--DEFINE oracle_db_name = 'ORAHOM';

CREATE STREAM IF NOT EXISTS STR_USER_SQLSERVER (
    after STRUCT <
        ID VARCHAR,
        USER_NAME VARCHAR,
        E_MAIL VARCHAR,
        USER_PASSWORD VARCHAR,
        CPF VARCHAR,
        CEP VARCHAR,
        COUNTRY VARCHAR,
        REGION VARCHAR,
        CITY VARCHAR,
        DISTRICT VARCHAR,
        STREET VARCHAR,
        STREET_NUMBER VARCHAR,
        USER_ESPA VARCHAR
    >,
    op VARCHAR
) WITH (KAFKA_TOPIC='master.dbo.USER_', VALUE_FORMAT='JSON');



CREATE STREAM IF NOT EXISTS USER_SQLSERVER AS SELECT 
    after -> ID AS ID,
    after -> USER_NAME AS USER_NAME,
    after -> E_MAIL AS E_MAIL,
    after -> USER_PASSWORD AS USER_PASSWORD,
    after -> CPF AS CPF,
    after -> CEP AS CEP,
    after -> COUNTRY AS COUNTRY,
    after -> REGION AS REGION,
    after -> CITY AS CITY,
    after -> DISTRICT AS DISTRICT,
    after -> STREET AS STREET,
    after -> STREET_NUMBER AS STREET_NUMBER,
    after -> USER_ESPA AS USER_ESPA,
    op VARCHAR
FROM STR_USER_SQLSERVER;

CREATE STREAM IF NOT EXISTS STR_USER_PURCHASE_SQLSERVER (
    after STRUCT <
        ID VARCHAR,
        VALUE_PURCHASE VARCHAR,
        USER_PURCHASE_ESPA VARCHAR,
        USER_ID VARCHAR
    >,
    op VARCHAR
) WITH (KAFKA_TOPIC='master.dbo.USER_PURCHASE', VALUE_FORMAT='JSON');

CREATE STREAM IF NOT EXISTS USER_PURCHASE_SQLSERVER AS SELECT 
    after -> ID AS ID,
    after -> VALUE_PURCHASE AS VALUE_PURCHASE,
    after -> USER_PURCHASE_ESPA AS USER_PURCHASE_ESPA,
    after -> USER_ID AS USER_ID,
    op VARCHAR
FROM STR_USER_PURCHASE_SQLSERVER;

CREATE STREAM IF NOT EXISTS SINK_USER AS SELECT
    USER_NAME AS USER_NAME,
    E_MAIL AS E_MAIL,
    USER_PASSWORD AS USER_PASSWORD,
    CPF AS CPF,
    880000 AS USER_ESPA
FROM USER_SQLSERVER WHERE USER_ESPA <> '220000';

CREATE STREAM IF NOT EXISTS STR_USER_POSTGRESQL (
    after STRUCT <
        ID VARCHAR,
        USER_NAME VARCHAR,
        E_MAIL VARCHAR,
        USER_PASSWORD VARCHAR,
        CPF VARCHAR,
        USER_ESPA VARCHAR
    >,
    op VARCHAR
) WITH (KAFKA_TOPIC='postgresql.public.user_', VALUE_FORMAT='JSON');

CREATE STREAM IF NOT EXISTS SINK_USER_ADRESS AS SELECT
    up.after -> ID AS USER_ID
    CEP AS CEP,
    COUNTRY AS COUNTRY,
    REGION AS REGION,
    CITY AS CITY,
    DISTRICT AS DISTRICT,
    STREET AS STREET,
    STREET_NUMBER AS STREET_NUMBER,
    880000 AS USER_ADRESS_ESPA
FROM USER_SQLSERVER us 
INNER JOIN STR_USER_POSTGRESQL up WITHIN 7 DAYS ON up.after -> CPF = us.CPF
WHERE USER_ESPA <> '220000';

CREATE STREAM IF NOT EXISTS STR_USER_ADDRESS_POSTGRESQL (
    after STRUCT <
        ID VARCHAR,
        CEP VARCHAR,
        COUNTRY VARCHAR,
        REGION VARCHAR,
        CITY VARCHAR,
        DISTRICT VARCHAR,
        STREET VARCHAR,
        STREET_NUMBER VARCHAR,
        USER_ADDRESS_ESPA VARCHAR,
        USER_ID VARCHAR
    >,
    op VARCHAR
) WITH (KAFKA_TOPIC='postgresql.public.user_', VALUE_FORMAT='JSON');

CREATE STREAM IF NOT EXISTS SINK_USER_PURCHASE AS SELECT
    uad.after -> ID AS USER_ADDRESS_ID,
    ups.VALUE_PURCHASE AS VALUE_PURCHASE,
    880000 AS USER_PURCHASE_ESPA
FROM USER_PURCHASE_SQLSERVER ups 
    INNER JOIN USER_SQLSERVER us WITHIN 7 DAYS ON ups.USER_ID = us.ID
    INNER JOIN STR_USER_POSTGRESQL up WITHIN 7 DAYS ON up.after -> CPF = us.CPF
    INNER JOIN STR_USER_ADDRESS_POSTGRESQL uad WITHIN 7 DAYS ON up.after -> ID = uad.after -> USER_ID
WHERE USER_PURCHASE_ESPA <> '220000';
