CREATE TABLE USER_ (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_NAME VARCHAR(100),
    E_MAIL VARCHAR(100),
    USER_PASSWORD VARCHAR(100),
    CPF VARCHAR(11) UNIQUE,
    CEP INT,
    COUNTRY VARCHAR(100),
    REGION VARCHAR(100),
    CITY VARCHAR(100),
    DISTRICT VARCHAR(100),
    STREET VARCHAR(100),
    STREET_NUMBER INT,
    USER_ESPA VARCHAR(100)
);

CREATE TABLE USER_PURCHASE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    VALUE_PURCHASE DECIMAL,
    USER_PURCHASE_ESPA VARCHAR(100),
    USER_ID INT REFERENCES USER_(ID)
);