CREATE TABLE USER_ (
    ID SERIAL PRIMARY KEY,
    USER_NAME VARCHAR(100),
    E_MAIL VARCHAR(100),
    USER_PASSWORD VARCHAR(100),
    CPF VARCHAR(11) UNIQUE,
    USER_ESPA VARCHAR(100)
);

CREATE TABLE USER_ADDRESS (
    ID SERIAL PRIMARY KEY,
    CEP VARCHAR(100),
    COUNTRY VARCHAR(100),
    REGION VARCHAR(100),
    CITY VARCHAR(100),
    DISTRICT VARCHAR(100),
    STREET VARCHAR(100),
    STREET_NUMBER INTEGER,
    USER_ADDRESS_ESPA VARCHAR(100),
    USER_ID INTEGER REFERENCES USER_(ID)
);

CREATE TABLE USER_PURCHASE (
    ID SERIAL PRIMARY KEY,
    VALUE_PURCHASE NUMERIC,
    USER_PURCHASE_ESPA VARCHAR(100),
    USER_ADDRESS_ID INTEGER REFERENCES USER_ADDRESS(ID)
);