

CREATE TABLE "USER_INSERT" (
    "ID" SERIAL PRIMARY KEY,
    "USER_NAME" VARCHAR(100),
    "E_MAIL" VARCHAR(100),
    "USER_PASSWORD" VARCHAR(100),
    "CPF" VARCHAR(11),
    "CEP" INT,
    "COUNTRY" VARCHAR(100),
    "REGION" VARCHAR(100),
    "CITY" VARCHAR(100),
    "DISTRICT" VARCHAR(100),
    "STREET" VARCHAR(100),
    "STREET_NUMBER" INT,
    "USER_ESPA" VARCHAR(100)
);

CREATE TABLE "USER_PURCHASE2" (
    "ID" SERIAL PRIMARY KEY,
    "VALUE_PURCHASE" NUMERIC,
    "USER_PURCHASE_ESPA" VARCHAR(100),
    "USER_ID" INTEGER REFERENCES "USER_INSERT"("ID")
);

INSERT INTO "USER_INSERT" ("USER_NAME", "E_MAIL", "USER_PASSWORD", "CPF", "CEP", "COUNTRY", "REGION", "CITY", "DISTRICT", "STREET", "STREET_NUMBER", "USER_ESPA")
VALUES ('Igor Tosta', 'igortosta@gmail.com', '123456789', '00000000000', 44990000, 'BRASIL', 
'BAHIA', 'BARRA DO MENDES', 'CENTRO', 'RUA SUSPEITA', 888, '220000');

INSERT INTO "USER_PURCHASE2" ("VALUE_PURCHASE", "USER_PURCHASE_ESPA", "USER_ID")
VALUES (8.55, '220000', 1);

INSERT INTO "USER_PURCHASE2" ("VALUE_PURCHASE", "USER_PURCHASE_ESPA", "USER_ID")
VALUES (180.54, '220000', 1);

INSERT INTO "USER_INSERT" ("USER_NAME", "E_MAIL", "USER_PASSWORD", "CPF", "CEP", "COUNTRY", "REGION", "CITY", "DISTRICT", "STREET", "STREET_NUMBER", "USER_ESPA")
VALUES ('Deyllon Pereira', 'deyllonperaira@gmail.com', '123456789', '00000000000', 99999999, 'BRASIL', 
'TODOS', 'TODAS', 'TUDO', 'TODAS AS RUAS', 999, '220000');

INSERT INTO "USER_PURCHASE2" ("VALUE_PURCHASE", "USER_PURCHASE_ESPA", "USER_ID")
VALUES (1904.74, '220000', 2);

INSERT INTO "USER_PURCHASE2" ("VALUE_PURCHASE", "USER_PURCHASE_ESPA", "USER_ID")
VALUES (1.74, '220000', 2);

